/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * SIMK Auth API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface User {
  id: string;
  email: string;
  createdAt: string;
}

export interface AuthResponse {
  /** JWT access token */
  accessToken: string;
  /** Optional if not using cookies */
  refreshToken?: string;
  /** Access token expiry in seconds */
  expiresIn: number;
  user: User;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
  requestId?: string;
}

/**
 * Invalid request
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Unauthorized
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * @summary Register a new user
 */
export const registerUser = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterRequest>> => {
    return axios.post(
      `/v1/auth/register`,
      registerRequest,options
    );
  }

/**
 * @summary Login using email and password
 */
export const loginUser = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    return axios.post(
      `/v1/auth/login`,
      loginRequest,options
    );
  }

/**
 * @summary Logout user (invalidate refresh token)
 */
export const logoutUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/v1/auth/logout`,undefined,options
    );
  }

export type RegisterUserResult = AxiosResponse<RegisterRequest>
export type LoginUserResult = AxiosResponse<AuthResponse>
export type LogoutUserResult = AxiosResponse<void>
